# frozen_string_literal: true

source 'https://rubygems.org'

gem 'mysql2', '~> 0.5.0'
gem 'cassandra-driver', '~> 3.2.0'

gem 'aws-sdk-s3', '~> 1.0'
gem 'ruby-kafka', '~> 0.7.0'

gem 'zlib', '~> 1.0.0'
gem 'rubyzip', '~> 1.2.0'
gem 'parslet', '~> 1.8.0'

gem 'daemons', '~> 1.2.0'