game_env: 'qaqc'
game_uuid: '7fc9e7c9-d622-4bee-a4e1-518a87435171'

aws_s3:
  s3_config:
    s3_bucket: xxx
    s3_client_config:
      region: us-east-1
      access_key_id: xxx
      secret_access_key: xxx

  remote_path: 'AssetUsage/{env}'
  local_path: '../_work/{env}'
  refresh_interval_sec: 300

mysql:
  mysql_config:
    host: xxx
    port: xxx
    username: omega_dev
    password: omega_dev@pass
    database: omega
    encoding: 'utf8'
  table_name: 'hsck_asset_report_{env}'
  db_single_insert: 100
